version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9000"
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: gotest
      MYSQL_PASSWORD: 1234