version: '3'

services:
  db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: "demo"
        MYSQL_USER: gotest
        MYSQL_PASSWORD: 1234
      restart: always
  go:
    build:
      context: .
      dockerfile: dockerfile
    links:
      - db
    ports:
      - 8080:8080
    depends_on:
      - "db"
volumes:
  mysql_data: